openapi: 3.0.0
info:
  title: Number Sum API
  version: 1.0.0
paths:
  /sum:
    post:
      summary: Compute sum of numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - numbers
              properties:
                numbers:
                  type: array
                  items:
                    type: number
      responses:
        '200':
          description: Sum result
          content:
            application/json:
              schema:
                type: object
                properties:
                  sum:
                    type: number
                  cached:
                    type: boolean
        '400':
          description: Invalid input
